databaseH2:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:test
  user: sa
  password: 
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  
server:
  type: simple
  applicationContextPath: /videoRentalStore
  adminContextPath: /admin
  connector:
    type: http
    port: 8088
    
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout