databasePostgres:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://192.168.99.100:5432/postgres
  user: user
  password: password
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  
server:
  type: simple
  applicationContextPath: /videoRentalStore
  adminContextPath: /admin
  connector:
    type: http
    port: 8088
    
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      
flywayLocations: classpath:db/migration/postgres,classpath:dev_sql